//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MuhasebeSistemiDBWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Siparisler
    {
        public int SiparisNo { get; set; }
        public string MusteriAdi { get; set; }
        public string UrunAdi { get; set; }
        public Nullable<int> UrunAdet { get; set; }
    }
}
